# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200)),
                ('command_date', models.DateTimeField(verbose_name='date of command')),
                ('command_status', models.CharField(choices=[('SCS', 'Success'), ('CNC', 'Could not connect to Arduino')], default='SCS', max_length=3)),
            ],
        ),
    ]
